# Generated by Django 5.1.4 on 2026-04-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="optionvalue",
            name="option_type",
        ),
        migrations.RemoveField(
            model_name="variant",
            name="option_values",
        ),
        migrations.RemoveField(
            model_name="product",
            name="has_variants",
        ),
        migrations.DeleteModel(
            name="OptionType",
        ),
        migrations.DeleteModel(
            name="OptionValue",
        ),
    ]
