# Generated by Django 5.1.4 on 2026-05-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_low_stock_threshold_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.DeleteModel(
            name="Variant",
        ),
    ]
