# Generated by Django 5.1.4 on 2026-05-02 23:34

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_add_sale_price_remove_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                max_length=200, upload_to=apps.products.models.product_image_upload_to
            ),
        ),
    ]
