# Generated by Django 5.1.4 on 2026-05-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_image_upload_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True, help_text="Emoji icon, e.g. 📱", max_length=10
            ),
        ),
    ]
