# Generated by Django 5.1.4 on 2026-05-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_add_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon_name",
            field=models.CharField(
                default="squares-four",
                help_text="Phosphor icon name (kebab-case, no ph- prefix). e.g. device-mobile, laptop",
                max_length=60,
            ),
        ),
    ]
