# Generated by Django 5.1.4 on 2026-04-25 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("new_order", "New Order"),
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("payment_failed", "Payment Failed"),
                            ("refund_success", "Refund Success"),
                            ("refund_failed", "Refund Failed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.CharField(max_length=300)),
                ("link", models.CharField(blank=True, max_length=200)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(default="Mutisya", max_length=200)),
                ("store_tagline", models.CharField(blank=True, max_length=300)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("physical_address", models.TextField(blank=True)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                (
                    "delivery_timeframe",
                    models.CharField(default="2-4 business days", max_length=100),
                ),
                ("notif_email", models.EmailField(blank=True, max_length=254)),
                ("notif_new_order", models.BooleanField(default=True)),
                ("notif_out_of_stock", models.BooleanField(default=True)),
                ("notif_low_stock", models.BooleanField(default=True)),
                ("notif_payment_failure", models.BooleanField(default=True)),
                ("notif_refund_outcome", models.BooleanField(default=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="store/")),
                (
                    "hero_headline",
                    models.CharField(
                        default="Tech That Moves With You.", max_length=200
                    ),
                ),
                ("hero_subheading", models.CharField(blank=True, max_length=300)),
                ("hero_overline", models.CharField(blank=True, max_length=200)),
                (
                    "hero_cta1_text",
                    models.CharField(default="Shop Now", max_length=100),
                ),
                (
                    "hero_cta1_link",
                    models.CharField(default="/products/", max_length=200),
                ),
                ("hero_cta2_text", models.CharField(blank=True, max_length=100)),
                ("hero_cta2_link", models.CharField(blank=True, max_length=200)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="store/"),
                ),
                ("story_heading", models.CharField(blank=True, max_length=120)),
                ("story_text", models.TextField(blank=True)),
                ("story_cta_text", models.CharField(blank=True, max_length=100)),
                ("story_cta_link", models.CharField(blank=True, max_length=200)),
                (
                    "story_image",
                    models.ImageField(blank=True, null=True, upload_to="store/"),
                ),
                ("section_hero_visible", models.BooleanField(default=True)),
                ("section_categories_visible", models.BooleanField(default=True)),
                ("section_featured_visible", models.BooleanField(default=True)),
                ("section_deals_visible", models.BooleanField(default=True)),
                ("section_bestsellers_visible", models.BooleanField(default=True)),
                ("section_story_visible", models.BooleanField(default=True)),
                ("section_testimonials_visible", models.BooleanField(default=True)),
                ("section_newsletter_visible", models.BooleanField(default=True)),
                (
                    "section_heading_featured",
                    models.CharField(default="Featured Products", max_length=100),
                ),
                (
                    "section_subheading_featured",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "section_heading_deals",
                    models.CharField(default="Today's Deals", max_length=100),
                ),
                (
                    "section_heading_bestsellers",
                    models.CharField(default="Best Sellers", max_length=100),
                ),
                (
                    "section_subheading_bestsellers",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "section_heading_newsletter",
                    models.CharField(default="Stay in the Loop", max_length=100),
                ),
                (
                    "section_subheading_newsletter",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "section_newsletter_fine",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "featured_categories",
                    models.ManyToManyField(blank=True, to="products.category"),
                ),
            ],
            options={
                "verbose_name": "Store Settings",
                "verbose_name_plural": "Store Settings",
            },
        ),
    ]
