# Generated by Django 5.1.4 on 2026-05-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomepageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Banner"),
                            ("categories", "Category Tiles"),
                            ("featured", "Featured Products"),
                            ("deals", "Deals / Flash Sales"),
                            ("bestsellers", "Best Sellers"),
                            ("story", "Brand Story"),
                            ("testimonials", "Testimonials"),
                            ("newsletter", "Newsletter Signup"),
                            ("custom_promo", "Promo Banner"),
                            ("custom_image_text", "Image + Text"),
                            ("custom_video", "Video Embed"),
                            ("custom_faq", "FAQ"),
                            ("custom_spotlight", "Product Spotlight"),
                            ("custom_countdown", "Countdown Timer"),
                            ("custom_richtext", "Rich Text"),
                            ("custom_html", "Custom HTML"),
                        ],
                        max_length=50,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("is_core", models.BooleanField(default=True)),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("1", "Variant 1"),
                            ("2", "Variant 2"),
                            ("3", "Variant 3"),
                        ],
                        default="1",
                        max_length=1,
                    ),
                ),
                (
                    "bg_mode",
                    models.CharField(
                        choices=[
                            ("colour", "Colour"),
                            ("image", "Image"),
                            ("image_overlay", "Image + Overlay"),
                        ],
                        default="colour",
                        max_length=15,
                    ),
                ),
                (
                    "bg_colour",
                    models.CharField(
                        choices=[
                            ("--navy", "Navy"),
                            ("--gold", "Gold"),
                            ("--emerald", "Emerald"),
                            ("--surface", "White"),
                            ("--surface-alt", "Light Grey"),
                            ("--text", "Dark"),
                        ],
                        default="--surface",
                        max_length=20,
                    ),
                ),
                (
                    "bg_image",
                    models.ImageField(blank=True, null=True, upload_to="sections/"),
                ),
                (
                    "bg_image_pos",
                    models.CharField(
                        choices=[
                            ("top left", "↖"),
                            ("top center", "↑"),
                            ("top right", "↗"),
                            ("center left", "←"),
                            ("center center", "·"),
                            ("center right", "→"),
                            ("bottom left", "↙"),
                            ("bottom center", "↓"),
                            ("bottom right", "↘"),
                        ],
                        default="center center",
                        max_length=20,
                    ),
                ),
                (
                    "bg_overlay_colour",
                    models.CharField(
                        choices=[
                            ("--navy", "Navy"),
                            ("--gold", "Gold"),
                            ("--emerald", "Emerald"),
                            ("--surface", "White"),
                            ("--surface-alt", "Light Grey"),
                            ("--text", "Dark"),
                        ],
                        default="--navy",
                        max_length=20,
                    ),
                ),
                ("bg_overlay_opacity", models.PositiveSmallIntegerField(default=40)),
                (
                    "spacing",
                    models.CharField(
                        choices=[
                            ("sm", "Small"),
                            ("md", "Medium"),
                            ("lg", "Large"),
                            ("xl", "Extra Large"),
                        ],
                        default="lg",
                        max_length=2,
                    ),
                ),
                (
                    "heading_colour",
                    models.CharField(
                        choices=[
                            ("--navy", "Navy"),
                            ("--gold", "Gold"),
                            ("--emerald", "Emerald"),
                            ("--surface", "White"),
                            ("--surface-alt", "Light Grey"),
                            ("--text", "Dark"),
                        ],
                        default="--text",
                        max_length=20,
                    ),
                ),
                (
                    "heading_size",
                    models.CharField(
                        choices=[
                            ("28px", "S"),
                            ("36px", "M"),
                            ("48px", "L"),
                            ("60px", "XL"),
                        ],
                        default="48px",
                        max_length=6,
                    ),
                ),
                (
                    "heading_weight",
                    models.CharField(
                        choices=[
                            ("300", "Light"),
                            ("400", "Regular"),
                            ("500", "Medium"),
                            ("600", "Bold"),
                        ],
                        default="600",
                        max_length=3,
                    ),
                ),
                (
                    "body_colour",
                    models.CharField(
                        choices=[
                            ("--navy", "Navy"),
                            ("--gold", "Gold"),
                            ("--emerald", "Emerald"),
                            ("--surface", "White"),
                            ("--surface-alt", "Light Grey"),
                            ("--text", "Dark"),
                        ],
                        default="--text-sub",
                        max_length=20,
                    ),
                ),
                (
                    "body_size",
                    models.CharField(
                        choices=[("14px", "S"), ("16px", "M"), ("18px", "L")],
                        default="16px",
                        max_length=5,
                    ),
                ),
                (
                    "body_weight",
                    models.CharField(
                        choices=[
                            ("300", "Light"),
                            ("400", "Regular"),
                            ("500", "Medium"),
                            ("600", "Bold"),
                        ],
                        default="400",
                        max_length=3,
                    ),
                ),
                (
                    "btn1_colour",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("--navy", "Navy"),
                            ("--gold", "Gold"),
                            ("--emerald", "Emerald"),
                            ("--surface", "White"),
                            ("--surface-alt", "Light Grey"),
                            ("--text", "Dark"),
                        ],
                        default="--navy",
                        max_length=20,
                    ),
                ),
                (
                    "btn1_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("filled", "Filled"),
                            ("outline", "Outline"),
                            ("ghost", "Ghost"),
                        ],
                        default="filled",
                        max_length=10,
                    ),
                ),
                ("btn1_enabled", models.BooleanField(default=True)),
                (
                    "btn2_colour",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("--navy", "Navy"),
                            ("--gold", "Gold"),
                            ("--emerald", "Emerald"),
                            ("--surface", "White"),
                            ("--surface-alt", "Light Grey"),
                            ("--text", "Dark"),
                        ],
                        default="--navy",
                        max_length=20,
                    ),
                ),
                (
                    "btn2_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("filled", "Filled"),
                            ("outline", "Outline"),
                            ("ghost", "Ghost"),
                        ],
                        default="outline",
                        max_length=10,
                    ),
                ),
                ("btn2_enabled", models.BooleanField(default=False)),
                ("custom_content", models.JSONField(blank=True, default=dict)),
                (
                    "inline_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="sections/inline/"
                    ),
                ),
                (
                    "inline_image_pos",
                    models.CharField(
                        choices=[("left", "Left"), ("right", "Right")],
                        default="right",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HomepageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                ("snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
