# Generated by Django 5.1.4 on 2026-05-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_seed_homepage_sections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storesettings",
            name="hero_headline",
            field=models.CharField(default="Tech That Moves With You.", max_length=80),
        ),
    ]
