# Generated by Django 5.1.4 on 2026-05-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_hero_headline_maxlength"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagesection",
            name="variant",
            field=models.CharField(
                choices=[
                    ("1", "Variant 1"),
                    ("2", "Variant 2"),
                    ("3", "Variant 3"),
                    ("4", "Variant 4"),
                    ("5", "Variant 5"),
                    ("6", "Variant 6"),
                ],
                default="1",
                max_length=1,
            ),
        ),
    ]
