# Generated by Django 5.1.4 on 2026-04-30 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0002_remove_optionvalue_option_type_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="variant",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="variant_name",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="variant",
        ),
    ]
