from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('stats/', views.home_stats_api, name='home_stats'),
    path('orders/', views.orders_list, name='orders'),
    path('orders/<str:order_number>/', views.order_detail, name='order_detail'),
    path('orders/<str:order_number>/status/', views.order_update_status, name='order_status'),
    path('orders/<str:order_number>/note/', views.order_add_note, name='order_note'),
    path('products/', views.products_list, name='products'),
    path('products/add/', views.product_add, name='product_add'),
    path('products/<int:pk>/', views.product_detail, name='product_detail'),
    path('products/<int:pk>/edit/', views.product_edit, name='product_edit'),
    path('products/<int:pk>/flags/', views.product_flag_toggle, name='product_flags'),
    path('products/<int:pk>/toggle/', views.product_toggle_visibility, name='product_toggle'),
    path('products/<int:pk>/stock/', views.product_update_stock, name='product_stock'),
    path('products/<int:pk>/delete/', views.product_delete, name='product_delete'),
    path('products/<int:pk>/set-cover/', views.set_cover, name='product_set_cover'),
    path('products/<int:pk>/reorder-images/', views.reorder_images, name='product_reorder_images'),
    path('analytics/', views.analytics, name='analytics'),
    path('analytics/revenue/', views.report_revenue, name='report_revenue'),
    path('analytics/top-products-units/', views.report_top_products_units, name='report_top_products_units'),
    path('analytics/top-products-revenue/', views.report_top_products_revenue, name='report_top_products_revenue'),
    path('analytics/top-customers/', views.report_top_customers, name='report_top_customers'),
    path('analytics/revenue-by-county/', views.report_revenue_by_county, name='report_revenue_by_county'),
    path('analytics/inventory/', views.report_inventory, name='report_inventory'),
    path('analytics/cart-abandonment/', views.report_cart_abandonment, name='report_cart_abandonment'),
    path('analytics/cohort-retention/', views.report_cohort_retention, name='report_cohort_retention'),
    path('payments/', views.payments_list, name='payments'),
    path('customers/', views.customers_list, name='customers'),
    path('customers/<int:pk>/', views.customer_detail, name='customer_detail'),
    path('customers/<int:pk>/ban/', views.customer_ban, name='customer_ban'),
    path('customers/<int:pk>/unban/', views.customer_unban, name='customer_unban'),
    path('customers/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('customers/<int:pk>/note/', views.customer_note_add, name='customer_note'),
    path('categories/', views.categories_list, name='categories'),
    path('categories/add/', views.category_add, name='category_add'),
    path('categories/<int:pk>/edit/', views.category_edit, name='category_edit'),
    path('categories/<int:pk>/delete/', views.category_delete, name='category_delete'),
    path('homepage/', views.homepage_editor, name='homepage_editor'),
    path('homepage/section/add/', views.homepage_section_add, name='homepage_section_add'),
    path('homepage/section/reorder/', views.homepage_section_reorder, name='homepage_section_reorder'),
    path('homepage/section/<int:pk>/save/', views.homepage_section_save, name='homepage_section_save'),
    path('homepage/section/<int:pk>/delete/', views.homepage_section_delete, name='homepage_section_delete'),
    path('upload-category-image/', views.upload_category_image, name='upload_category_image'),
    path('upload-story-image/', views.upload_story_image, name='upload_story_image'),
    path('homepage/template/save/', views.homepage_template_save, name='homepage_template_save'),
    path('homepage/template/<int:pk>/load/', views.homepage_template_load, name='homepage_template_load'),
    path('settings/hero-content/', views.homepage_hero_content_save, name='homepage_hero_content_save'),
    path('settings/footer/', views.footer_settings_save, name='footer_settings_save'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]
